version: '3'

services:
  # bot:
  #   build: 
  #     context: .
  #   network_mode: host
  #   command: ["bash", "-c", "npm run migrations && npm run watch"]
  #   volumes:
  #     - './src:/app/src'
  db:
    image: 'postgres:9.6'
    ports:
      - 5432:5432
    volumes: 
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"