version: '3'

services:
  db:
    image: 'postgres:9.6'
    ports:
      - 5432:5432
    volumes: 
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
